### ISSUE TITLE
Can I use yacrd to remove palindromes in long reads obtained from MDA?

### ISSUE THREAD

**Issue by ilnamkang** [natir/yacrd#30]
Hi!

I'd like to know if I can use yacrd to scrub long reads obtained from MDA samples, specifically in terms of removing palindromes.

If I run yacrd in a scrubbing mode, can I expect that yacrd would remove palindromes in long reads introduced by MDA?

Actually, I've tried to use Pacasus, a tool developed specifically to correct palindromes in long reads from MDA. (https://github.com/swarris/Pacasus)
But, unfortunately, I haven't succeeded in installing the tool on my system.

Thanks.

Ilnam

**Comment by natir** [comment]
Unfortunately I don't know if yacrd can do that.

yacrd is based on the idea that regions with a lot of errors have less overlap with the reads of their dataset. I don't know how minimap2 is going to behave with these regions.

The best would be to do a test with a reads that you were sure contains a palindrome and to analyze the overlap found by minimap on this reads. If we have less overlap on region of palindrome yacrd can probably help you.

If you have any other question or if you need help to found the good set of parametre for minimap2 and yacrd don't hessitate to ask.

**Comment by ilnamkang** [comment]
Thank you for a quick reply.

Aside from this issue, I'd like to let you know that yacrd much improved the assembly quality of several of my non-MDA genomes. I've used the Flye assembler following yacrd for my PacBio P6-C4 reads.

Thanks for a great tool.

Ilnam

**Comment by natir** [comment]
Thank you for your feedback I had not yet tested the effects of yacrd on flye assemblies. I'm glad to hear that my work has been able to help you.

Did you use the parameters recommended in the readme for the P6-C4 reads? Or did you modify them?

**Comment by ilnamkang** [comment]
I used the parameters recommended for the P6-C4 in the readme without any modification.

I'm a little bit curious whether these parameters can have huge effects on the final assembly quality, because several of my genomes got much benefit from yacrd, while several others didn't.

**Comment by natir** [comment]
For P6-C4 we select this parameter because they optimize the NGA50 and misassemblies metrics of [Pacbio C. elegans dataset](https://github.com/PacificBiosciences/DevNet/wiki/C.-elegans-data-set).

Maybe with a larger testing dataset some other value can be found, but I think we are not to fare to the best one.

To explain yacrd has only a small effect on some assemblies and has a very important effect on others, I think sometimes yacrd just eliminates the reads or read region that caused problems for the assemblers and sometimes not. 

This lack of regularity is a problem, if you want and can I would like to study these assemblies.

**Comment by ilnamkang** [comment]
Thanks for a detailed explanation.

I'd like to, but I can't share these assemblies currently. These assemblies are from several Streptomyces strains. My colleagues are working on these strains to find and patent novel bioactive materials.

**Comment by natir** [comment]
Thanks for your feedback !
