### ISSUE TITLE
Comparisons with MiniScrub

### ISSUE THREAD

**Issue by FSciammarella** [natir/yacrd#31]
Hello, @natir,

I'm currently looking into long read scrubbing and came about your tools and publications, and the comparison with DASCRUBBER, but you just briefly mention MiniScrub. 

Do you have or know of any comparisons on effect of MiniScrub vs yacrd?

Greetings.

**Comment by natir** [comment]
I made comparisons with miniscrub but only on a small set of nanopore data. [Section 5 of the supplemental information](https://www.biorxiv.org/content/biorxiv/early/2019/06/19/674036/DC1/embed/media-1.pdf?download=true)

Because unfortunately, I do not have a computer with GPUs supporting Tensorflow or Keras, without this support the computation time was too important.
