### ISSUE TITLE
Kernel panic  at 'called `Option::unwrap()`

### ISSUE THREAD

**Issue by FSciammarella** [natir/yacrd#33]
Hello, @natir,

I tried running yacrd to scrub my reads and got the following output:

>thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21
>note: Run with `RUST_BACKTRACE=1` for a backtrace.

I ran the script like this:
```sh
minimap2 -x ava-ont -g 500 SRR10150407_1_merged.fq.gz SRR10150407_1_merged.fq.gz > overlap.paf
yacrd scrubbing -c 3 -n 0.4 -m overlap.paf -s SRR10150407_1_merged.fq.gz -S reads_scrubbed.fasta -r scrubbed_report.yacrd
```

Cheers

**Comment by natir** [comment]
Hi, @FSciammarella,

Are you sure all input file exist ? isn't empty ? and it can be read by the launch user ?

Can you run and give to me the output please:
```
RUST_BACKTRACE=1 yacrd scrubbing -c 3 -n 0.4 -m overlap.paf -s SRR10150407_1_merged.fq.gz -S reads_scrubbed.fasta -r scrubbed_report.yacrd
```
Thank

**Comment by natir** [comment]
I remembered a similar bug, and in fact you have the same problem. #28 

Unfortunately the current release of yacrd does not accept the extensions.fa and.fq you have to use .fasta and .fastq.

This problem will be fixed in the next version but for the bypassed you only have to rename your reads file (or just create a symbolic link).

```
mv SRR10150407_1_merged.fq.gz SRR10150407_1_merged.fastq.gz
```

Once again, I'm sorry.

Best.
