### ISSUE TITLE
Detection of chimeras in nanopore reads

### ISSUE THREAD

**Issue by fernanarr** [natir/yacrd#52]
Hi,

We are trying to detect chimeras in some nanopore 16s reads. Although we already know that there are some chimeras in our reads, we are not able to detect them using the parameters from the yacrd example:

`minimap2 -x ava-ont -g 500 reads.fasta reads.fasta > overlap.paf`
`yacrd -i overlap.paf -o report.yacrd -c 4 -n 0.4 scrubb -i reads.fasta -o reads.scrubb.fasta`

Could you please help us with the correct parameters to use for this detection?

Thanks in advance.

Regards

**Comment by natir** [comment]
Thanks for using yacrd

Important point:
- yacrd has been tested only on DNA direct sequencing data
- you used parameters optimized for read scrubbing not [chimera detection](https://github.com/natir/yacrd#find-chimera)

Can you give me a little more information on the sequencing protocol, PCR amplifications, read selection, nanopore sequencing cell version?

**Comment by fernanarr** [comment]
Hello again,

Thanks for your quick response.

The data we work with have been obtained from an amplification of the complete 16RNA gene from a known mixture of bacteria,( Gut Zymobiomics standard, (about 15 different species)).

The amplicon obtained has been sequenced with the R10 4 1 ONT flowcell and then classified with EMU (https://www.nature.com/articles/s41592-022-01520-4).

In a detailed analysis we have seen that out of about 20000 reads 5% are chimerical, being able to identify the origin of the chimerical reads. We have seen that Latorre (https://github.com/adlape95/Spaghetti) says that in a similar assay he is able to identify and eliminate chimeras using yacrd, but we have not been able to reproduce the results with our data, as we did not detect any chimera.

Could you please help us with the parameters to modify to see if we are able to get any results?

Thanks in advance for your help.

**Comment by natir** [comment]
I tried to contact the authors of Spaghetti to tell them that they didn't use yacrd with a good parameter for chimera detection in my opinion. It's interesting to scrub reads, but it's not the same operation as chimera detection. But I haven't been able to get an answer.

Since you're multiplying reads by PCR, I'm assuming you've got a very high coverage rate, but you may also have duplicating chimeras.

Yacrd analyzes the coverage of each read to determine whether it is chimeric or not. You can try increasing the value of the `-c` parameter, which corresponds to the minimum coverage value at which a read is considered to have a poor quality region. If a read has a poor-quality region in the middle, it's considered chimeric.

I recommend you play with this parameter on a subset of reads, including reads you're sure are chimeric, to find the best `-c` values for your dataset.

This should enable you to discover reads that have become chimeric after or during PCR multiplication. But for reads that were "generated" before PCR multiplication and therefore multiplied by it, yacrd won't be able to help you.

**Comment by fernanarr** [comment]
Hi @natir ,

First of all, thanks a lot for all your help and efforts with yacrd.

I've been making some trials modifying the -c parameter. I've tried values going from 50 to 10000 but, although now yacrd finds some chimeras, I'm not getting the amount of chimeric detections needed.

I'll try some more values to check if I can get all the chimeras from the reads.

Thanks again for your quick responses and for your help.

**Comment by natir** [comment]
Be careful with very large values of `-c`, there may be many false positives.

I'm interested in feedback to possibly add recommendations to the Readme.

I close the issue, but do not hesitate to repost a message with your conclusion.

**Comment by fernanarr** [comment]
Hi @natir 

I'm affraid that, in this particular case, yacrd is not correctly identifiyng the chimeras that I have already identified manually

I've been trying several values for -c and I get many "not covered" reads and not all the chimeras that it should identify.

Thanks anyway for all your usefull help

Regards

**Comment by Robvh-git** [comment]
@fernanarr @natir 

I also want to detect chimeras on 16S nanopore data. I've tried vsearch now, but as vsearch was developed for high quality short reads, I think a lot of false positive chimeric sequences are found. 

@natir you state "If a read has a poor-quality region in the middle, it's considered chimeric.". But - if I'm not mistaken - this does not lead to correct chimera detection of amplicon chimeras? In amplicon sequencing the error profile (i.e. the poor-quality region) is not related to the read being chimeric or not. 

So can I state correctly that yacrd is not suitable for chimera detection of amplicon nanopore data?
